apiVersion: apps/v1
kind: Deployment
metadata:
  name: perware-deployment
spec:
  selector:
    matchLabels:
      app: perware
  replicas: 2
  template:
    metadata:
      labels:
        app: perware
    spec:
      containers:
      - name: perware
        image: perware
        imagePullPolicy: Never
        ports:
          - containerPort: 5000
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
          requests:
            memory: "500Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 5000
            httpHeaders:
            - name: Accept
              value: application/json
          initialDelaySeconds: 10
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: perware-service
spec:
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  selector:
    app: perware
  type: LoadBalancer